name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn test --coverage --json --outputFile=result.json --testLocationInResults
        env:
          CI: true
      - uses: tanmen/jest-reporter@master
        if: always()
        with:
          action-name: jest report (${{ matrix.node-version }})
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn depcheck
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  notify:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ needs.test.result }}
          job_name: Test
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
